### PR TITLE
fix(evm): revert precompile

### LINKED ISSUE #70: [BUG] can not catch the error returned by precompiled contracts in EVM
## Summary of Bug

For ordinary contracts, when calling their functions with `try/catch` clause or low level call, if the function returns an error, the error should be caught and not bubbled up. But for precompiled contracts, it has different behavior: it would revert the whole tx even if `try/catch` or low level call is used

This issue is the root cause of another issue: https://github.com/ExocoreNetwork/exocore-contracts/issues/39
## Additional context

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

### PR DESCRIPTION
**Pull request by MaxMustermann2**
needs dependencies to be merged first

Step 1 https://github.com/imua-xyz/cosmos-sdk/pull/1

Step 2 https://github.com/imua-xyz/evmos/pull/7

Step 3 This PR

## Summary by CodeRabbit

- **Chores**
  - Updated dependency sources to enhance functionality and support for new features.
  - Adjusted configuration values, including gateway addresses and token thresholds, to ensure smoother local operations.

- **Refactor**
  - Streamlined backend processing for transaction execution and state management, enhancing reliability and performance.
  - Introduced dedicated routines for clearing outdated state data, supporting more robust account operations.
  - Enhanced error handling and input validation in various precompile methods to improve robustness.
  - Added new methods for managing state and code deletions, improving code modularity.

- **New Features**
  - Introduced new smart contracts (`Gateway`, `GatewayCaller`, `GatewayCallee`, `UnknownMethodCaller`, `PrecompileCallerThatReverts`, `ThirdPartyCallee`, and `TryCatchCaller`) with functionalities for asset management, revert handling, and error capturing.
  - Added JSON files for ABI and binary code of new contracts, facilitating interaction with the blockchain.
  - Implemented a new function for validating transaction methods, enhancing error handling during execution.

- **Tests**
  - Added new test suite for validating wrapped revert scenarios in smart contracts, ensuring robust error handling during asset operations.
  - Added a new test suite for testing unknown method calls on precompiles, ensuring graceful handling of such scenarios.
  - Improved error handling and state management in existing test cases for better reliability.
  - Enhanced log checking with expected data validation for emitted events.

### CODE REVIEW

**Review by TimmyExogenous — APPROVED** [review]
LGTM

File: precompiles/assets/assets.go [hunk 1]
```diff
@@ -183,6 +177,10 @@ func (p Precompile) Run(evm *vm.EVM, contract *vm.Contract, readOnly bool) (bz [
 		return nil, vm.ErrOutOfGas
 	}
 
+	if err := p.AddJournalEntries(stateDB, snapshot); err != nil {
+		return nil, err
+	}
+
```
[the remark this answers is not in the document]
Comment (MaxMustermann2) [reply precompiles/assets/assets.go]: We can examine two scenarios in which this limit may be triggered by a caller.
1. Wrapped in a try catch: added unit test for such a situation
2. Not wrapped in a try catch: the overall tx fails and hence it is never committed to state

**Review by leonz789 — APPROVED** [review]

**Review by trestinlsd — APPROVED** [review]

File: precompiles/assets/assets.go [hunk 2]
```diff
@@ -86,9 +85,9 @@ func (p Precompile) Run(evm *vm.EVM, contract *vm.Contract, readOnly bool) (bz [
 	// It avoids panics and returns the out of gas error so the EVM can continue gracefully.
 	defer cmn.HandleGasError(ctx, contract, initialGas, &err)()
 
-	if err := stateDB.Commit(); err != nil {
-		return nil, err
-	}
+	// we cache the context because we consume the failure, if any, in this function.
+	// cascading it to statedb is possible but we will lose foundry compatibility
+	// see https://github.com/imua-xyz/imuachain/issues/70
```
Comment (adu-web3) [inline precompiles/assets/assets.go]: #70 is not about foundry compatibility, so we can remove this comment

File: precompiles/assets/assets.go [hunk 3]
```diff
@@ -86,9 +85,9 @@ func (p Precompile) Run(evm *vm.EVM, contract *vm.Contract, readOnly bool) (bz [
...
 	cc, writeFunc := ctx.CacheContext()
```
Comment (adu-web3) [inline precompiles/assets/assets.go]: both evmos's patch and cronos's implementation seems not having this, does it mean it is safe to remove this?

File: precompiles/assets/assets.go [hunk 4]
```diff
@@ -183,6 +178,16 @@ func (p Precompile) Run(evm *vm.EVM, contract *vm.Contract, readOnly bool) (bz [
 		return nil, vm.ErrOutOfGas
 	}
 
+	if p.IsTransaction(method.Name) {
```
Comment (adu-web3) [inline precompiles/assets/assets.go]: this `isTransaction` is not safe: if some newly added method would write the store but is forgotten to be declared in `p.IsTransaction`, this function would return false. Given `isTransaction` is enforced by precompile interface, could we add a new function like `safeIsTransaction` that would return an error if it is not declared?

File: precompiles/assets/testdata/Gateway.sol [hunk 5]
```diff
@@ -0,0 +1,65 @@
...
+    }
+
+    function withdrawLSTAndThenRevert(
+        uint32 clientChainID,
+        bytes calldata assetsAddress,
+        bytes calldata withdrawAddress,
+        uint256 opAmount
+    ) public returns (bool success, uint256 latestAssetState) {
+        (success, latestAssetState) = withdrawLST(clientChainID, assetsAddress, withdrawAddress, opAmount);
+        revert("Intentional revert after withdraw");
```
Comment (adu-web3) [inline precompiles/assets/testdata/Gateway.sol]: The scenario that reflects the problem this time is not a direct revert following the precompile call, but calling another contract after calling the precompile and revert in this outcome call. So instead of directly reverting here, we should call another contract here and make that call revert

Comment (MaxMustermann2) [reply precompiles/assets/testdata/Gateway.sol]: Gateway is not called in the unit test. Instead, GatewayCaller calls gateway.

**Comment by adu-web3** [comment]
btw, would we also patch the balance discrepancy issue in this PR, or in `statedb` of our evmos fork? And it may not be related to this, but Cronos's implementation inspires us that we could convert native event logs emitted in modules as `ethlogs` to be emitted in evm, which should help improve contract development, I could open another PR to see if this works

File: precompiles/assets/testdata/Gateway.sol (hunk 5 above)
Comment (adu-web3) [reply precompiles/assets/testdata/Gateway.sol]: Yeah, I mean the old node would not trigger the error if we directly revert after calling the precompile in the same function, unless we call another contract and revert there, according to my test

File: precompiles/assets/assets.go (hunk 3 above)
Comment (MaxMustermann2) [reply precompiles/assets/assets.go]: Added comment to indicate that it will be done in the next PR.

File: precompiles/assets/assets.go (hunk 4 above)
Comment (MaxMustermann2) [reply precompiles/assets/assets.go]: Changed `IsTransaction` to `panic` in the `default` situation and captured this `panic` in `init` to force developers to remember this.

**Review by adu-web3 — APPROVED** [review]

File: precompiles/assets/testdata/Gateway.sol (hunk 5 above)
Comment (MaxMustermann2) [reply precompiles/assets/testdata/Gateway.sol]: Updated so that a callee contract is responsible for the revert instead.

File: precompiles/common/is_tx.go [hunk 6]
```diff
@@ -0,0 +1,67 @@
...
+		return fmt.Errorf("error parsing the ABI %s", err)
+	}
+
+	// sort for determinism
+	// although this method is only used during `init()` currently,
+	// this is a form of future-proofing.
+	methods := make([]string, 0, len(abi.Methods))
+	for _, method := range abi.Methods {
+		methods = append(methods, method.Name)
+	}
```
[the remark this answers is not in the document]
Comment (MaxMustermann2) [reply precompiles/common/is_tx.go:34]: This iteration is performed to sort the map's keys. The sorted keys are then iterated over.

File: precompiles/assets/testdata/PrecompileCallerThatReverts.sol [hunk 7]
```diff
@@ -0,0 +1,214 @@
...
+            name, 
+            metadata, 
+            oracleInfo
+        );
+        
+        if (!registered) {
+            bool updated = ASSETS_CONTRACT.updateToken(clientChainIdUint32, token, metadata);
+            require(updated, "Failed to update token");
+        }
+    }
```
[the remark this answers is not in the document]
Comment (MaxMustermann2) [reply precompiles/assets/testdata/PrecompileCallerThatReverts.sol:201]: Test; not relevant.

File: precompiles/assets/testdata/PrecompileCallerThatReverts.sol [hunk 8]
```diff
@@ -0,0 +1,214 @@
...
+        (bool success,) = ASSETS_CONTRACT.registerOrUpdateClientChain(
+            uint32(clientChainId), 
+            stakerAccountLength, 
+            name, 
+            metadata, 
+            signatureScheme
+        );
+        
+        require(success, "Failed to register client chain");
+    }
```
[the remark this answers is not in the document]
Comment (MaxMustermann2) [reply precompiles/assets/testdata/PrecompileCallerThatReverts.sol:176]: Test; not relevant.

File: precompiles/assets/testdata/PrecompileCallerThatReverts.sol [hunk 9]
```diff
@@ -0,0 +1,214 @@
...
+            amount
+        );
+        address target = address(ASSETS_CONTRACT);
+        assembly {
+            let ptr := add(data, 0x20)
+            success := call(
+                gasLimit, target, 0, add(data, 0x20), mload(data), ptr, 0x20
+            )
+            success := and(success, mload(ptr))
+        }
```
[the remark this answers is not in the document]
Comment (MaxMustermann2) [reply precompiles/assets/testdata/PrecompileCallerThatReverts.sol:134]: Removed function `callPrecompileAndRevertGasStarved`

**Comment by adu-web3** [comment]
all e2e test cases have passed, excellent work!

File: precompiles/slash/slash.go [hunk 10]
```diff
@@ -112,16 +101,21 @@ func (p Precompile) Run(evm *vm.EVM, contract *vm.Contract, readOnly bool) (bz [
...
+// IsTransaction checks if the given methodName corresponds to a transaction or query.
+func (Precompile) IsTransaction(methodName string) bool {
+	switch methodName {
 	case MethodSlash:
 		return true
 	default:
-		return false
+		panic(fmt.Sprintf("unknown method: %s", methodName))
+	}
+}
```
[the remark this answers is not in the document]
Comment (MaxMustermann2) [reply precompiles/slash/slash.go]: The `init` takes care of this. However, I have added a comment as you advised referring to the upstream guarantees.

File: precompiles/bls/bls.go [hunk 11]
```diff
@@ -45,21 +44,19 @@ func NewPrecompile() (*Precompile, error) {
...
 // RequiredGas calculates the precompiled contract's base gas rate.
 func (p Precompile) RequiredGas(input []byte) uint64 {
-	if len(input) < 4 {
-		return 0
-	}
 	method, err := p.MethodById(input)
 	if err != nil {
 		return 0
 	}
+	// TODO: @devin: add gas calculation depending on the method
```
[the remark this answers is not in the document]
Comment (MaxMustermann2) [reply precompiles/bls/bls.go]: Removed TODO since it was already implemented.

File: precompiles/bech32/bech32.go [hunk 12]
```diff
@@ -50,53 +51,64 @@ func NewPrecompile(authzKeeper authzkeeper.Keeper) (*Precompile, error) {
...
+	if err != nil {
+		// this will (might?) cause the entire tx to fail.
+		// it is acceptable because it would represent an error
+		// in the precompile caller.
+		return nil, err
 	}
-	return nil, nil
+
+	return bz, nil
 }
```
[the remark this answers is not in the document]
Comment (MaxMustermann2) [reply precompiles/bech32/bech32.go:94]: Pointless suggestion given the interface guard `var _ vm.PrecompiledContract = &Precompile{}` on top of the file.
